Parameters:
  ReactAppAllowedCidr:
    Type: String
    Description: "Allowed CIDR block (X.X.X.X/X) for React App UI access"
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in format x.x.x.x/x
  TavilyApiKey:
    Type: String
    NoEcho: true
    Description: Provide TavilyApiKey API Key to utilize /web_search path
    MinLength: 1
  USPTOApiKey:
    Type: String
    NoEcho: true
    Description: Provide USPTO API Key to utilize /search path
    MinLength: 1

Resources:
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-hcls-ml.s3.us-east-1.amazonaws.com/public_assets_support_materials/hcls_agent_toolkit/packaged_app.yaml
      Parameters:
        ReactAppAllowedCidr: !Ref ReactAppAllowedCidr
      TimeoutInMinutes: 35

  ClinicalTrialProtocolSupervisorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AppStack
    Properties:
      TemplateURL: https://aws-hcls-ml.s3.us-east-1.amazonaws.com/public_assets_support_materials/hcls_agent_toolkit/packaged_clinical-trial-protocol-assistant-cfn.yaml
      TimeoutInMinutes: 35

  CompetitiveIntelligenceSupervisorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AppStack
    Properties:
      TemplateURL: https://aws-hcls-ml.s3.us-east-1.amazonaws.com/public_assets_support_materials/hcls_agent_toolkit/packaged_competitive-intelligence-agent-cfn.yaml
      Parameters:
        TavilyApiKey: !Ref TavilyApiKey
        USPTOApiKey: !Ref USPTOApiKey
      TimeoutInMinutes: 35

  WileyOnlineSearchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AppStack
    Properties:
      TemplateURL: https://aws-hcls-ml.s3.us-east-1.amazonaws.com/public_assets_support_materials/hcls_agent_toolkit/packaged_wiley-search-agent-cfn.yaml
      TimeoutInMinutes: 35

Outputs:
  ReactAppExternalURL:
    Value:
      Fn::GetAtt:
        - AppStack
        - Outputs.ReactAppExternalURL
    Description: ALB DNS for the React App
  AgentRole:
    Value:
      Fn::GetAtt:
        - AppStack
        - Outputs.AgentRole
    Description: Amazon Bedrock Agents Service Role ARN
