AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the Competitive Intelligence supervisor agent.
Parameters:
  AgentAliasName:
    Type: String
    Default: "Latest"
  BedrockModelId:
    Type: String
    Description: The ID of the Foundation Model to use for the Agent
    Default: us.anthropic.claude-3-5-sonnet-20241022-v2:0
  AgentIAMRoleArn:
    Type: String
    Description: (Optional) Amazon Bedrock Agents service role ARN
    Default: ""
  TavilyApiKey:
    Type: String
    NoEcho: true
    Description: Provide TavilyApiKey API Key to utilize /web_search path
    MinLength: 1
  USPTOApiKey:
    Type: String
    NoEcho: true
    Description: Provide USPTO API Key to utilize /search path
    MinLength: 1
  S3Bucket:
    Description: Name of the S3 bucket to use for deployment and run storage
    Type: String
    Default: ""

Conditions:
  CreateAgentAliasCondition: !Not [!Equals [!Ref AgentAliasName, ""]]
  AgentIAMRoleCondition: !Not [!Equals [!Ref AgentIAMRoleArn, ""]]
  AgentS3BucketCondition: !Not [!Equals [!Ref S3Bucket, ""]]

Resources:
  #####################
  ##### Agent #####
  ###################

  WebSearchAgentStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/agents_catalog/packaged_web-search-agent-cfn.yaml
      Parameters:
        AgentAliasName: "Latest"
        AgentIAMRoleArn: !Ref AgentIAMRoleArn
        TavilyApiKey: !Ref TavilyApiKey
      TimeoutInMinutes: 35

  SEC10kAgentStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/agents_catalog/packaged_sec-10-K-agent-cfn.yaml
      Parameters:
        AgentAliasName: "Latest"
        AgentIAMRoleArn: !Ref AgentIAMRoleArn
        S3CodeBucket:
          "Fn::If":
            - AgentS3BucketCondition
            - !Ref S3Bucket
            - "{{resolve:ssm:/s3/agent_build/name:1}}"
      TimeoutInMinutes: 35

  USPTOSearchAgentStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/agents_catalog/packaged_uspto-search-agent-cfn.yaml
      Parameters:
        AgentAliasName: "Latest"
        AgentIAMRoleArn: !Ref AgentIAMRoleArn
        USPTOApiKey: !Ref USPTOApiKey
      TimeoutInMinutes: 35

  CompetitiveIntelligenceAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      ActionGroups:
        - ActionGroupName: "UserInputAction"
          ParentActionGroupSignature: "AMAZON.UserInput"
          ActionGroupState: "ENABLED"
      AgentCollaboration: "SUPERVISOR"
      AgentCollaborators:
        - CollaboratorName: Web-Search-Agent
          AgentDescriptor:
            AliasArn: !GetAtt WebSearchAgentStack.Outputs.AgentAliasArn
          CollaborationInstruction: |
            Use the Web Search Agent to:
              - Find breaking news and recent developments
              - Track mergers, acquisitions, and partnership announcements
              - Monitor leadership changes and executive statements
              - Identify new product launches or service offerings
              - Gather analyst opinions and market reactions
              - Research competitor moves affecting the target company
              - Track regulatory developments or legal challenges
              - Find recent earnings call summaries and guidance updates
            Focus searches on content from the past 3-6 months to complement the historical data from SEC filings with current market context.
        - CollaboratorName: SEC-10-K-Search-Agent
          AgentDescriptor:
            AliasArn: !GetAtt SEC10kAgentStack.Outputs.AgentAliasArn
          CollaborationInstruction: |
            Use SEC 10-K Search Agent when you need specific quantitative financial information such as:
              - Revenue figures and year-over-year growth
              - Profit margins and earnings data
              - Balance sheet metrics
              - Cash flow information
              - Debt levels and financing activities
        - CollaboratorName: USPTO-Search-Agent
          AgentDescriptor:
            AliasArn: !GetAtt USPTOSearchAgentStack.Outputs.AgentAliasArn
          CollaborationInstruction: |
            Use USPTO Search Agent when you need information about patent applications, such as:
              - Recent patent applications on given topic
              - The inventor, filing date, or applicant of a given patent

      AgentName: Competitive-Intelligence-Agent
      # If an IAM role ARN is passed as a paremter, use it. Otherwise look in SSM parameter store
      AgentResourceRoleArn:
        "Fn::If":
          - AgentIAMRoleCondition
          - !Ref AgentIAMRoleArn
          - "{{resolve:ssm:/bedrock/agent/role/arn:1}}"
      AutoPrepare: True
      Description: "Analyze business, financial, and patent information using search"
      FoundationModel: !Ref BedrockModelId
      GuardrailConfiguration:
        GuardrailIdentifier: !GetAtt CompetitiveIntelGuardrail.GuardrailId
        GuardrailVersion: !GetAtt CompetitiveIntelGuardrail.Version
      Instruction: |
        You are an expert Corporate Competitive Intelligence Analyst powered by AI. Your purpose is to create comprehensive competitive 
        intelligence reports on major US corporations by analyzing recent activities, market positioning, and financial trends.

        Your Capabilities:

        You can coordinate three specialized sub-agents to gather information:

            - Web Search Agent: Can retrieve recent news articles, press releases, analyst reports, and media coverage about target companies
            - SEC Filing Agent: Can extract and analyze data from SEC 10-K filings
            - USPTO Search Agent: Can retrieve and analyze patent applications from the USPTO

        Report Structure:

        Your competitive intelligence reports should follow this format:

            1. Executive Summary (Key findings and strategic implications in 2-3 paragraphs)
            2. Company Overview (Brief description, sector, market cap, core business lines)
            3. Recent Developments (Key news, product launches, leadership changes, strategic shifts)
            4. Financial Performance Analysis
                - Revenue trends and growth rates
                - Profitability metrics (margins, ROI, etc.)
                - Balance sheet health
                - Cash flow patterns
                - Key financial ratios compared to industry benchmarks
            5. Strategic Initiatives (Recent or ongoing)
            6. Competitive Position (Market share, positioning relative to key competitors)
            7. Risk Factors (Regulatory, market, operational challenges)
            8. Future Outlook (Analyst projections, guidance, growth vectors)

        Working Process:

            1. First, understand the specific company the user wants analyzed
            2. Instruct the Web Search Agent to find recent news about the company (last 3-6 months)
            3. Direct the SEC Filing Agent to retrieve relevant data about profit and loss from the previous 5 years of 10-K filings
            4. Ask the USPTO search agent to find patent applications from the past 365 days with the name of the company or any research topics identified in the web search
            5. Synthesize information from all sources into a cohesive narrative
            6. Identify patterns, anomalies, and strategically significant insights
            7. Present findings objectively with relevant quantitative data
            8. Format the report professionally with clear section headings

        Guidelines:

            - Maintain objectivity and avoid speculation
            - Support claims with specific data points and citations
            - Highlight the strategic implications of financial trends
            - Compare financial metrics to relevant industry benchmarks
            - Focus on material developments that impact company valuation or strategic position
            - Provide proper attribution for all information sources
            - Note any significant data limitations or areas requiring further research
            - Use professional, clear language appropriate for business executives

        When a user requests a competitive intelligence report, ask clarifying questions if needed to understand exactly which company to analyze and any specific aspects of interest.

  AgentAliasResource:
    Type: AWS::Bedrock::AgentAlias
    Condition: CreateAgentAliasCondition
    Properties:
      AgentId: !GetAtt CompetitiveIntelligenceAgent.AgentId
      AgentAliasName: !Ref AgentAliasName

  CompetitiveIntelGuardrail:
    Type: AWS::Bedrock::Guardrail
    Properties:
      BlockedInputMessaging: "Sorry, your query violates our usage policies."
      BlockedOutputsMessaging: "Sorry, I am unable to reply because the output violates our usage policies."
      ContentPolicyConfig:
        FiltersConfig:
          - InputStrength: "LOW"
            OutputStrength: "LOW"
            Type: "SEXUAL"
          - InputStrength: "LOW"
            OutputStrength: "LOW"
            Type: "VIOLENCE"
          - InputStrength: "LOW"
            OutputStrength: "LOW"
            Type: "HATE"
          - InputStrength: "LOW"
            OutputStrength: "LOW"
            Type: "INSULTS"
          - InputStrength: "LOW"
            OutputStrength: "LOW"
            Type: "MISCONDUCT"
          - InputStrength: "LOW"
            OutputStrength: "NONE"
            Type: "PROMPT_ATTACK"
      Description: Turn on to block profane words and other harmful content.
      Name: CompetitiveIntelGuardrail
      WordPolicyConfig:
        ManagedWordListsConfig:
          - Type: PROFANITY

Outputs:
  AgentId:
    Description: Agent ID
    Value: !Ref CompetitiveIntelligenceAgent
  AgentAliasId:
    Description: Agent Alias ID
    Value: !GetAtt AgentAliasResource.AgentAliasId
    Condition: CreateAgentAliasCondition
  AgentAliasArn:
    Description: Agent Alias ARN
    Value: !GetAtt AgentAliasResource.AgentAliasArn
    Condition: CreateAgentAliasCondition
